source $HOME/.zsh/functions.zsh
source $HOME/.zsh/options.zsh
source $HOME/.zsh/keybindings.zsh
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/theme.zsh
source $HOME/.zsh/plugins.zsh
[ -f ~/.zsh/hosts/$(md5h).zsh ] && source $HOME/.zsh/hosts/$(md5h).zsh

# vim: ft=zsh
