# attach to tmux session if connected via ssh, create new if none exists
if [[ $- == *i* ]] && [[ -z "$TMUX" ]] && [[ -n "$SSH_CONNECTION" ]]; then
      tmux new-session -t main || tmux new-session -s main
fi

source $HOME/.zsh/functions.zsh
source $HOME/.zsh/options.zsh

envvar_path_prepend PATH "$HOME/bin"
envvar_path_prepend PATH "$HOME/local/bin"
envvar_path_prepend PATH "$HOME/.local/bin"

source $HOME/.zsh/keybindings.zsh
source $HOME/.zsh/aliases.zsh
source $HOME/.zsh/theme.zsh
source $HOME/.zsh/plugins.zsh
[ -f ~/.zsh/hosts/$(md5h).zsh ] && source $HOME/.zsh/hosts/$(md5h).zsh

# vim: ft=zsh
